### GET / 
GET http://localhost:3000

### POST /auth/register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
   "username": "User123",
   "password": "123"
}

### POST /auth/login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
   "username": "User123",
   "password": "123"
}